# Generated by Django 3.2 on 2021-05-04 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('startDate', models.DateTimeField()),
                ('details', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Goer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch', models.BooleanField(default=False)),
                ('goer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goer', to='areyougoingapi.goer')),
                ('watched_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_user', to='areyougoingapi.goer')),
            ],
        ),
        migrations.CreateModel(
            name='UsersEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areyougoingapi.event')),
                ('goer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areyougoingapi.goer')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='goer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areyougoingapi.goer'),
        ),
    ]
